baseURL = "https://www.matiasilva.com"
languageCode = "en-us"
title = "matias silva"

[params]
    description = "Engineering undergrad at the University of Cambridge"

[markup]
[markup.highlight]
codeFences = true
noClasses = false

[menu]

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2

  [[menu.main]]
    name = "Journal"
    url = "/journal/"
    weight = 3

  [[menu.main]]
    name = "CV"
    url = "/files/Matias_CV_2021.pdf"
    weight = 4

[taxonomies]
  tag = "tags"